//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCrm.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Note
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public int CompanyId { get; set; }
        public int PersonId { get; set; }
        public Nullable<int> TaskId { get; set; }
        public int TaskId1 { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Person Person { get; set; }
        public virtual Task Task { get; set; }
    }
}
